#!/usr/bin/env python3

from typing import Callable
from argparse import ArgumentParser
from toXComposeTools import uhex2xc, uhex2xc_web


def main(hexstr: str, keys: str,
         usr_hex2xc: Callable[[str, str], str]) -> None:

    print(usr_hex2xc(hexstr, keys))


if __name__ == '__main__':
    args = ArgumentParser(
        description="Returns a string formatted for inclusion in XCompose")

    args.add_argument('hexstr', help='The hex codepoint of the character to look up')
    args.add_argument('--keys',
                      default='<Multi_key> ',
                      type=str,
                      help='Key combo string for XCompose.')
    args.add_argument('-w', '--web',
                      action='store_true',
                      help='Use Internet resources to obtain \
                unicode character data.')

    args = args.parse_args()

    if args.hexstr is None:
        raise ValueError('Must specify a character to lookup.')

    if args.web:
        usr_hex2xc = uhex2xc_web
    else:
        usr_hex2xc = uhex2xc

    main(args.hexstr, args.keys, usr_hex2xc)
